services:
  - type: web
    name: pgadmin-render
    env: docker
    plan: free
    disk:
      name: pgadmin-data
      mountPath: /var/lib/pgadmin
      sizeGB: 1
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        sync: false
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false
